### ISSUE TITLE
bump dependency pyyaml>=4.2b1

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/cloud-debug-python#11]
Otherwise any github project importing this package shows a high-severity security alert:

https://github.com/GoogleCloudPlatform/microservices-demo/blob/31df60f050a113c771a91477863ce93c8ed0f078/src/recommendationservice/requirements.txt#L30

![image](https://user-images.githubusercontent.com/159209/52014321-148c2780-2494-11e9-951c-4ce2af194aa7.png)

**Comment by hrasadi** [comment]
Thanks for bringing this into our attention. We are working on fixing the dependencies and will soon release an update

**Comment by hrasadi** [comment]
Done with the release of agent version 2.10. We now use pyyaml 5.1.
