### ISSUE TITLE
arm support

### ISSUE THREAD

**Issue by minusplusminus** [GoogleCloudPlatform/cloud-debug-python#12]
Hi,

I was wondering if ARM support will be there in the future?

**Comment by di** [comment]
Currently this project only publishes [`manylinux1`](https://www.python.org/dev/peps/pep-0513/) wheels, which are limited to the `x86_64` and `i686` architectures. Supporting ARM would require publishing [`manylinux2014`](https://www.python.org/dev/peps/pep-0599/) wheels.
