### ISSUE TITLE
ERROR: No matching distribution found for google-python-cloud-debugger

### ISSUE THREAD

**Issue by ex-nerd** [GoogleCloudPlatform/cloud-debug-python#13]
As referenced in #8, this is still an issue with Python 3.7 in MacOS.  I can see `google-python-cloud-debugger (2.13)`  using `pip search` but when I go to install it, I get:

```
ERROR: Could not find a version that satisfies the requirement google-python-cloud-debugger (from versions: none)
ERROR: No matching distribution found for google-python-cloud-debugger
```

**Comment by materemias** [comment]
I tried to install it on alpine 3.7 and it failed with the same error message as well.

**Comment by jakebiesinger-onduo** [comment]
+1 using `pipenv` for python 3.7 and google_python_cloud_debugger versions 2.11 through 2.13.

```
$ pipenv install google-python-cloud-debugger
 
['ERROR: Could not find a version that satisfies the requirement google-python-cloud-debugger==2.13 (from -r /var/folders/rr/psl1scpj14g69hdx_ghmtds00000gq/T/pipenv-lrebcgjc-requirements/pipenv-hagaz92p-requirement.txt (line 1)) (from versions: none)', 'ERROR: No matching distribution found for google-python-cloud-debugger==2.13 (from -r /var/folders/rr/psl1scpj14g69hdx_ghmtds00000gq/T/pipenv-lrebcgjc-requirements/pipenv-hagaz92p-requirement.txt (line 1))']
```

The `(from versions: none)` makes me think that there simply isn't an `egg` for darwin-- look over at https://github.com/GoogleCloudPlatform/cloud-debug-python/releases and notice there's only `source` and `py3.7-linux-x86_64.egg`

**Comment by bscott3** [comment]
Any news on this?

**Comment by ex-nerd** [comment]
I just sent an email with this ticket to cdbg-feedback@google.com (as per the repository's README)

It's also word noting that you *can* get this to compile on MacOS via:

* `brew install cmake`
* Update `src/setup.py` to remove `'rt'` from line 100
* `cd src && ./build.sh`

HOWEVER... attempting to `import googleclouddebugger` results in `cannot import name 'cdbg_native' from 'googleclouddebugger'` errors, so it's less than useful.

**Comment by sbrieuc** [comment]
Still nothing on this ?

**Comment by Gaket** [comment]
The same issue with google-python-cloud-debugger==2.14.

Moreover, can't get it installed in AppEngine as well.

Getting:

```
FETCHSOURCE
Initialized empty Git repository in /workspace/.git/
error: RPC failed; HTTP 400 curl 22 The requested URL returned error: 400
fatal: the remote end hung up unexpectedly
error: RPC failed; HTTP 400 curl 22 The requested URL returned error: 400
fatal: the remote end hung up unexpectedly
error: RPC failed; HTTP 400 curl 22 The requested URL returned error: 400
fatal: the remote end hung up unexpectedly
ERROR
ERROR: error fetching repo source: generic::unknown: retry budget exhausted (3 attempts): fetching git source: error fetching git source: source fetch exited with non-zero status: 128
```

**Comment by di** [comment]
Per https://github.com/GoogleCloudPlatform/cloud-debug-python/issues/9#issuecomment-413664044, this library designed only to work on Linux (with glibc), and only publishes built distributions (wheels) for Linux.

If you're getting the `No matching distribution found for google-python-cloud-debugger` error, this means that you are attempting to install it on an incompatible platform, like macOS, or a Linux platform that does not use glibc (like the `alpine` images).

If you'd like to request that this project publish generic wheels that work on any platform, https://github.com/GoogleCloudPlatform/cloud-debug-python/issues/9 is an existing issue for that request.

**Comment by di** [comment]
@Gaket That looks like a different problem, can you open a new issue with more details?

**Comment by ex-nerd** [comment]
@di I think the main issue here for me is that it's very difficult to use this library while developing something for App Engine, since it requires the library be added to a requirements.txt file ... which then breaks local development.  I'm still looking into the use of conditional requirements per [PEP 508](https://www.python.org/dev/peps/pep-0508/) (e.g. `google-python-cloud-debugger; sys_platform == 'linux'`) but it would be nice if there as an easy way to make this package "work" on other platforms, even if  "work" is simply "installs a dummy package that prints a log message that it doesn't do anything" (which is more or less what's being asked in #9)

It would also help if all of this information about it being linux-only was covered explicitly (and easily visible) in the package documentation.

Anyway, since this is clearly a dupe of #9, I'll close this issue and follow that one.

**Comment by di** [comment]
@ex-nerd I think those are definitely two valid issues that are separate from #9:

* Ability for this package to be "mocked" in local development on non-Linux platforms
* Better documentation about the lack of compatibility platforms that aren't Linux

I'd encourage you to create new issues for those if you're able, but I'm happy to do it for you if you'd prefer, let me know.

**Comment by ex-nerd** [comment]
@di Go for it.

**Comment by di** [comment]
Made #18 and #19, thanks!
