### ISSUE TITLE
Ability for this package to be "mocked" in local development on non-Linux platforms

### ISSUE THREAD

**Issue by di** [GoogleCloudPlatform/cloud-debug-python#18]
_Originally posted by @ex-nerd in https://github.com/GoogleCloudPlatform/cloud-debug-python/issues/13#issuecomment-631147822_:

> I think the main issue here for me is that it's very difficult to use this library while developing something for App Engine, since it requires the library be added to a requirements.txt file ... which then breaks local development.  I'm still looking into the use of conditional requirements per [PEP 508](https://www.python.org/dev/peps/pep-0508/) (e.g. `google-python-cloud-debugger; sys_platform == 'linux'`) but it would be nice if there as an easy way to make this package "work" on other platforms, even if  "work" is simply "installs a dummy package that prints a log message that it doesn't do anything"

This could be done by providing a source distribution that short-circuits (possibly with a log message) when invoked on a non-Linux platform.

Note that this is different from #9, which is asking for a universal wheel that works the same on all platforms.

**Comment by msmans** [comment]
Any update or ETA on this?
