### ISSUE TITLE
Please add support for Python 3

### ISSUE THREAD

**Issue by salberin** [GoogleCloudPlatform/cloud-debug-python#2]
The current cloud debugger looks like a very nice addition to Google's cloud effort. But unfortunately I'm unable to examine it as all of our code is written in Python 3.5. Please extend the support to Python 3 as well...

**Comment by b-daniels** [comment]
Sorry for the delayed response here. Python 3 support is on our roadmap, but it's not at all clear when we'll get to it. Since Python 3 is still in active development, we want to modify the interpreter to provide some of the breakpoint support we need, instead of updating our Python 2.x bytecode rewrite logic to work with Python 3.

**Comment by paultiplady** [comment]
Thanks for the update @b-daniels -- if I'm interpreting that correctly, it would suggest that any existing Python3 interpreters would not be supported, and only hypothetical future Python3 releases with additional features will work with Google Cloud Debugger. Is that correct?

If that is so, please note that it will significantly delay adoption of this tool, since many distros (e.g. Debian) won't include a new Python version until it's been battle-tested in the wild for some time. For example, Debian Jessie is still on Python 3.4, even though it was released over 2.5 years ago.

**Comment by b-daniels** [comment]
The problem is that the current implementation rewrites bytecode, and we'd prefer not to go through all of the python 3 revisions to ensure we rewrite the bytecode correctly. Modifying the interpreter does slow adoption, but long term, it provides the best benefit for all users of Python without introducing a lot of risk.

**Comment by ManuelGysin** [comment]
We are also waiting for Python3 support. It's now 8 years since release.

> Python 3.0 final was released on December 3rd, 2008.

**Comment by ManuelGysin** [comment]
Are there any news or mail list entries to view the progress? @b-daniels 

> As a final heads up, Django 1.11 is likely to be the last version to support Python 2.7

Django 2.0 is target for Dec 17. The train to target 3.6 is gone, 3.7 will not be release before 2018-06-15.

[Django Roadmap](https://www.djangoproject.com/weblog/2015/jun/25/roadmap/)
[Python 3.7 Roadmap](https://www.python.org/dev/peps/pep-0537/)

This means we have at least 6 months no debug support on all newer django project, which are using 
 >= django 2, if the changes are landing in 3.7. Else there seems a long road ahead without debug support.

In my opinion this is are very costly trade off while using GCE with its stackdriver integration. We are using Container Engine and having a plugable debug agent is a must have. Using some other third party products is just PITA in the view of using stackdriver as a centralized service.

**Comment by skunkwerk** [comment]
Python 3 support would be wonderful, as none of our production code runs legacy 2.7 - and stackdriver debugger is an incredibly powerful tool.

**Comment by Jastrzebowski** [comment]
11 months have passed, Django 2.0 alpha is here, any news? 🤔

**Comment by ManuelGysin** [comment]
Seems this repo is abandoned, sad. 😪

**Comment by erezhaba** [comment]
Hi all, thank you very much for all the input, we will consider prioritizing cloud debugger for Python 3 and will update this issue soon.

**Comment by alexvanboxel** [comment]
We see a lot of action on other StackDriver debuggers (Node, Ruby, Java, ...) but Python 3 support is long overdue.

We're using Python 3 on some of our Kubernetes containers.

**Comment by davidebelloni** [comment]
+1

**Comment by ibrmora** [comment]
+1

**Comment by sdouche** [comment]
As a very old Python community member, I explain all the time to everybody to drop Python 2 and to use absolutely Python 3. So I think any GCP services which don't support Python 3 are astonishing.

**Comment by timc3** [comment]
+1

**Comment by gelbander** [comment]
+1

**Comment by kwiesmueller** [comment]
The ticket is quite old now, for us the entire debugging part is useless until there is support for python 3.x so are there any updates?

**Comment by erezhaba** [comment]
Hi all, thank you for your interest.  We are actively implementing a Python 3 debugger agent.
If you are interested in participating in testing the Alpha version and provide feedback, please let me know.

**Comment by thomasfowler** [comment]
We would love to participate in this. Is there a Gitter / Slack / Google Group etc where we can discuss? I assume this Github issue isn't the forum for signing up for a closed Alpha... ?

**Comment by kwiesmueller** [comment]
Would be happy to help too.

**Comment by paultiplady** [comment]
I'd be interested in participating too.

**Comment by Jastrzebowski** [comment]
Count me in :D

**Comment by sdouche** [comment]
I'm ready to test it.

**Comment by erezhaba** [comment]
Thank you all. We'll post here instructions on how to join the alpha once the agent is ready and past internal testing. I expect this to happen in 3-4 weeks.

**Comment by erezhaba** [comment]
Update: we're on track for beta testing in two weeks.  The initial agent release is for Python 3.6 (only), which is what we're able to test/verify at the moment. Please let me know if you have any request re this version.

**Comment by kwiesmueller** [comment]
3.6 Sounds great so far.
Looking forward to test.

**Comment by erezhaba** [comment]
Hi all, happy Friday!

I'm happy to let you know that we've release the debugger agent for Python 3.6. Please regard this release as an alpha version. Although it passes all tests, it still doesn't have the mileage that the Python 2.7 agent has.
We are looking forward for your feedback. Please give it a go.

You can find the agent (v2.5) on [PyPy](https://www.google.com/url?q=https://pypi.python.org/pypi?:action%3Ddisplay%26name%3Dgoogle-python-cloud-debugger%26version%3D2.5&sa=D&source=hangouts&ust=1521321722815000&usg=AFQjCNEPMu-ghFOymQ0Xfyn4-3Oi3GASlg) or on this repo.  The instruction to installare the same (module py version) as the Python 2.7 agent.

Thanks,
Erez and the Stackdriver Debugger team

**Comment by kwiesmueller** [comment]
Should we post feedback about the 3.6 here or in new issues?

**Comment by erezhaba** [comment]
Both are okay. you can also email cdbg-feedback@google.com for an interactive response.

**Comment by alexvanboxel** [comment]
I just tried our first Python3 micro-service (Python 3.6) with the new debugger and works nicely. A few things are annoying (like the use of the mandatory old project number), but I could get around it by just entering the project_id twice.

Also, it's maybe time to think about having a **Alpine** build (very popular with micro services).

**Comment by erezhaba** [comment]
Thanks Alex,
If you run on GCP you don't need to follow the service-account instructions and specify project information. The agent reads that from the metadata service.

**Comment by erezhaba** [comment]
FYI, a new version for the Python 3.6 agent was released today, agent version 2.8. with several fixes including,

- Removes static linking of libstdc++
- Uses application default credentials, removing any need for any flags if they are available
