### ISSUE TITLE
Use environment markers in setup.py

### ISSUE THREAD

**Issue by s2terminal** [GoogleCloudPlatform/cloud-debug-python#23]
I think the `setup.py` in this repository is switching requirements by `if` statements.
https://github.com/GoogleCloudPlatform/cloud-debug-python/blob/93aad83f61e8e41a870239e15134d555254079db/src/setup.py#L110-L112

How about using [environment markers](https://www.python.org/dev/peps/pep-0496/) instead of switching requirements?

## Backgrounds
I want to install `google-python-cloud-debugger` with Python 3.9 and [Poetry](https://python-poetry.org/), but it couldn't because of version solving error of `google-api-python-client==1.8.4`.

According to [this issue](https://github.com/python-poetry/poetry/issues/1551#issuecomment-551250223), it seems that Poetry does not execute the setup.py file when resolving dependencies. So `if` statements are not working when using Poetry.

**Comment by mctavish** [comment]
Resolved in https://github.com/GoogleCloudPlatform/cloud-debug-python/commit/37c4486e3944ee24e123d4dc4b8a7bc940a6d671
