### ISSUE TITLE
Support for WSGI applications

### ISSUE THREAD

**Issue by paultiplady** [GoogleCloudPlatform/cloud-debug-python#3]
It's not clear to me whether it's possible to configure cloud-debug-python to work with a WSGI application like Django running in Google Compute Engine / Google Container Engine. Is this supported?

**Comment by b-daniels** [comment]
It is possible. Follow the instructions at https://cloud.google.com/debugger/docs/setting-up-python-on-compute-engine, except you will most likely want to attach the debugger in your wsgi.py. It can actually be attached from any code that will run exactly once, though.

**Comment by Pal0r** [comment]
Hey Paul, did you get this up and running with your Django App? I've added the following to my wsgi file:
`import os

from django.core.wsgi import get_wsgi_application


try:
    import googleclouddebugger
    googleclouddebugger.AttachDebugger(
        version='v1.0',
        module='django_app'
    )
except ImportError:
    pass

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "hueya_app.settings")

application = get_wsgi_application()`

But am not sure sure if this is the correct way.

**Comment by erezhaba** [comment]
Take a look at this repo docs, it has been updated to reflect Django support.

**Comment by erezhaba** [comment]
Issue is well documented.
