### ISSUE TITLE
Ending support for Python 2.7

### ISSUE THREAD

**Issue by busunkim96** [GoogleCloudPlatform/cloud-debug-python#30]
Hi,

I work on the Google Cloud Client Libraries team. I noticed that this package depends on `google-api-core`. We're planning to officially remove 2.7 support (require >=3.6) in `google-api-core` soon.

Is there a timeline for removing 2.7 support from this package? If there are no blockers I am happy to open a PR to update `setup.py`. 😄 

Thanks!

**Comment by mctavish** [comment]
Hey, sorry for the delay in the response here.  The short answer is that it's complicated, and we don't have a timeline for removing support yet.  That being said, we're already pinned to an old version of google-api-core for our Python 2.7 support so I hope that we are not a blocker for your efforts.

**Comment by mctavish** [comment]
I'm repurposing this issue for the general cleanup and removal of Python 2.7 support in this library.
