### ISSUE TITLE
Bump dependency pyyaml>=5.4

### ISSUE THREAD

**Issue by ckim328** [GoogleCloudPlatform/cloud-debug-python#34]
Similar to https://github.com/GoogleCloudPlatform/cloud-debug-python/issues/11

Otherwise any github project importing this package shows a critical severity security alert (ie. microservices-demo):
https://github.com/GoogleCloudPlatform/microservices-demo/blob/055772a9edfa1cc9669dcfa5d3762124af810b9e/src/recommendationservice/requirements.txt#L33

![Screen Shot 2022-01-07 at 3 41 30 PM](https://user-images.githubusercontent.com/35876108/148604671-779929ea-834e-463e-87cf-d6af266b239c.png)

**Comment by mctavish** [comment]
Looks like re-pinning dependencies on the microservices-demo pulled in the newer version of PyYAML.
