### ISSUE TITLE
cartservice:ed19dc5fcfff76ebc9e1627a7a291dc5f3e85d9f45b5bfe85cd47755a568a1a0 -> Failed

### ISSUE THREAD

**Issue by ezelanza** [GoogleCloudPlatform/cloud-debug-python#36]
Hey there.

I'm trying to run the demo locally and when I do the skaffold run command I'm getting the following error.

I'm trying in a Mac M1.

 - cartservice:ed19dc5fcfff76ebc9e1627a7a291dc5f3e85d9f45b5bfe85cd47755a568a1a0 -> Failed
loading images into kind nodes: unable to load image "cartservice:ed19dc5fcfff76ebc9e1627a7a291dc5f3e85d9f45b5bfe85cd47755a568a1a0" into cluster: running [kind load docker-image --name kind cartservice:ed19dc5fcfff76ebc9e1627a7a291dc5f3e85d9f45b5bfe85cd47755a568a1a0]
 - stdout: ""
 - stderr: "Image: \"cartservice:ed19dc5fcfff76ebc9e1627a7a291dc5f3e85d9f45b5bfe85cd47755a568a1a0\" with ID \"sha256:ed19dc5fcfff76ebc9e1627a7a291dc5f3e85d9f45b5bfe85cd47755a568a1a0\" not yet present on node \"kind-control-plane\", loading...\nERROR: failed to load image: command \"docker exec --privileged -i kind-control-plane ctr --namespace=k8s.io images import -\" failed with error: exit status 1\n\nCommand Output: unpacking docker.io/library/cartservice:ed19dc5fcfff76ebc9e1627a7a291dc5f3e85d9f45b5bfe85cd47755a568a1a0 (sha256:601ec5c92cd7e6fc792504c599d7f5b6d33fd31a64f3306fe347835de7931e95)...ctr: content digest sha256:98bc857b3aed80d40d9eb6695b20d06dba236abb0f94b6d413e182448f0027e9: not found\n"
 - cause: exit status 1,

Thanks!

**Comment by mctavish** [comment]
This error doesn't look like it's related to the Cloud Debugger product.  Is this for https://github.com/GoogleCloudPlatform/microservices-demo?

As an aside: I'll take this opportunity to once again apologize for the fact that the Cloud Debugger does not work on Macs.
