### ISSUE TITLE
Support for gunicorn

### ISSUE THREAD

**Issue by dennymarcels** [GoogleCloudPlatform/cloud-debug-python#60]
Hi! I could find no definitive answer but it seems the debugger does not work if the app is deployed via gunicorn. Is that so? If that is the case, is there any way to debug an app running with gunicorn as its entrypoint? Thank you.

**Comment by mayanksingh2298** [comment]
Hi @dennymarcels .. any update on this? Or did you solve it?

**Comment by dennymarcels** [comment]
Hi @mayanksingh2298 I did manage to make it work, only it was not related to gunicorn. I don't remember the details, but I believe in the very end I only made sure the package was installed in my app environment, and it was enabled at the beginning of my code, as per the Cloud Debugger's instructions.
One thing though, support to that debugger is being shut down on June, so it may not be worth trying to make it work.

**Comment by mctavish** [comment]
Sorry for not getting to this issue!

Yes, the debugger does absolutely work with gunicorn, though figuring out why things aren't working right can be tricky.

As for the longevity of the product, yes, it is being shut down very shortly.  The agent has been modified to work with Firebase as a backend though, so you should still be able to debug for some time: https://github.com/GoogleCloudPlatform/cloud-debug-python#snapshot-debugger---firebase-realtime-database-backend.  Note that your tools for interacting with the debugger will need to change to what is offered at https://github.com/GoogleCloudPlatform/snapshot-debugger
