### ISSUE TITLE
Support for asynchronous frameworks

### ISSUE THREAD

**Issue by mayanksingh2298** [GoogleCloudPlatform/cloud-debug-python#85]
Does this work for asynchronous python frameworks like sanic?

I wrote a simple webserver using sanic:
```
@app.route("/")
def hello(request):
    return json({"message": f"Hello, Sanic {tmp}!"})

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000)
```

And it doesn't seem to handle breakpoints in hello() function

**Comment by mctavish** [comment]
I can confirm that the Debugger does work in sanic.  Make sure that you have the agent installed, that you have appropriate credentials provided to it, and that you're enabling the agent early on in your application.  Check the logs for errors; most of the time the problems lie with authentication.

I'm going to take this moment to also push you towards trying the snapshot debugger, which uses Firebase as a backend.  The current Cloud Debugger product is deprecated and will be shut down shortly, so it'd be better to devote your efforts towards the longer-lasting option.

See https://github.com/GoogleCloudPlatform/cloud-debug-python#snapshot-debugger---firebase-realtime-database-backend

**Comment by mayanksingh2298** [comment]
Ah I think I figured it out. I wasn't handling the case of using multiple workers correctly.
Thanks @mctavish
