### ISSUE TITLE
No platform agnostic wheel for 2.9 release available in pip

### ISSUE THREAD

**Issue by dhendry** [GoogleCloudPlatform/cloud-debug-python#9]
* We are using pipenv and recently started seeing the following error:

```
pipenv install --dev
Installing dependencies from Pipfile.lock (971a5b)...
An error occurred while installing google-python-cloud-debugger==2.9! Will try again.
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 104/104 — 00:00:17
Installing initially failed dependencies...
Collecting google-python-cloud-debugger==2.9 0:00:00

  Could not find a version that satisfies the requirement google-python-cloud-debugger==2.9 (from -r /var/folders/zv/_xh5321j79scjr2wf9vtxvj40000gn/T/pipenv-s5oapd0h-requirements/pipenv-1yvnce3b-requirement.txt (line 1)) (from versions: 2.5, 2.6, 2.7, 2.8)
No matching distribution found for google-python-cloud-debugger==2.9 (from -r /var/folders/zv/_xh5321j79scjr2wf9vtxvj40000gn/T/pipenv-s5oapd0h-requirements/pipenv-1yvnce3b-requirement.txt (line 1))
```

* Further investigation shows that the latest 2.9 release has only been built with a `manylinux1_x86_64` platform target, ex from https://pypi.org/simple/google-python-cloud-debugger/

![image](https://user-images.githubusercontent.com/2521996/44231129-0d35c380-a16b-11e8-8847-fb7f7be1bd7d.png)

* Our code switches on enabling the cloud debugger based on whether its running on GCE but we still want to have access to the package on dev machines to avoid conditional imports and specialized requirements files.

**Comment by xinghuadou-google** [comment]
Are your dev machines OS X? The python debugger uploaded to PyPI has never worked on anything other than Linux. Do you want us to keep uploading it as none-any even though it won't work?

**Comment by dhendry** [comment]
Yes, that would be very useful. Again, our code never actually attaches the debugger unless its running in GCE however having a consistent requirements file and/or Pipfile we can use everywhere is very convenient. Dealing with a runtime if statement around `googleclouddebugger.enable()` is significantly easier than having to conditionally install pip packages.

**Comment by xinghuadou-google** [comment]
Sorry, we want to use the proper abi tags on PyPI going forward. We've had reports in the past where people tried to install on OS X and were confused on why it failed when they imported googleclouddebugger.

I'm not too familiar with pipenv, but could markers solve your issue?
https://github.com/pypa/pipfile#pep-508-support
